
VERILOG_FILES = \
	m1_alu.v \
	m1_core.v \
	m1_cpu.v \
	m1_defs.vh \
	m1_div.v \
	m1_mul.v 


obj_dir/Vm1_core : vmain.cpp $(VERILOG_FILES)
	verilator --cc m1_core.v --exe vmain.cpp
	NO_VCD_TRACE=1; make -C obj_dir/ -f Vm1_core.mk

clean :
	rm -rf obj_dir
	rm -f test.vcd



